### ISSUE TITLE
Segmentation fault on batch insertion

### ISSUE THREAD

**Issue by koeppl** [TooBiased/DySECT#2] opened 2020-01-01 03:20 UTC
The following modification of the provided example leads to a segmentation fault on line 14 when accessing an invalid reference returned by the `operator[]`. `find(i)` also gives the `end()` iterator despite having inserted `i`.
I've tested this behavior with g++ version 8.3.0 and clang++ version 7.0.1-8.

```
#include "utils/hash/murmur2_hash.h"
#include "include/cuckoo_dysect.h"


int main(int, char**) {
    size_t capacity = 100;
    using key_type    = size_t;
    using mapped_type = size_t;
    dysect::cuckoo_dysect<key_type, mapped_type> dysect_standard(capacity, 1.5);
	for(size_t i = 0; i < capacity/2; ++i) {
		dysect_standard.insert(i,i);
	}
	for(size_t i = 0; i < capacity/2; ++i) {
		 dysect_standard[i] = i;
	}
}
```

**Comment by TooBiased** [comment] 2020-06-15 12:12
Hi,
sorry I didn't see this issue, until I was made aware of the footnote in your SEA paper.
I am pretty sure the problem you encounter is, that the item is not fully inserted. This can be found by looking at the return value of insert operations (i.e. it should not be the end() iterator).

Especially in these really small tables i.e. 100 slots it is quite common, that no displacement path can be found. Bounds for cuckoo hashing are usually only accurate for large tables.

As soon as I have some time I will update this answer (after I have checked out the specific problem.)

**Comment by TooBiased** [comment] 2021-01-26 13:54
I am sorry for the late reply, but I cannot reproduce the problem, even with the version of the code that was up to date, when you filed your complaint. The problem should definitely be that find(i) returns end() after i was unsuccessfully inserted before. What I cannot explain is why such an early insertion could be unsuccessful.

If you used a version that was pulled prior to Apr. 2018, then there could be an explanation for the unsuccessful insertion in this really old version, the default replacement algorithm used to be a dummy, i.e. elements would not have been moved between buckets thus elements were just inserted into the emptier of their two choices. From that version on, the displacements would default to a bfs search, which should have found a slot.

I will close this issue, if similar problems still exist pleas open another issue, with more information about  how I can reproduce the problem.

**Closed as completed by TooBiased** 2021-01-26 13:55 UTC

**Comment by TooBiased** [comment] 2021-01-26 14:04
I also updated the readme explaining the possibility of unsuccessful insertions and their consequences.

**Comment by koeppl** [comment] 2021-02-24 09:23
Thanks! I can verify that the code now works.

**Comment by TooBiased** [comment] 2021-02-24 09:25
Great, glad I could help.
